// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvolqsppxwwouhejnssd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2b2xxc3BweHd3b3VoZWpuc3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTUzNDYsImV4cCI6MjA3MTQzMTM0Nn0.oNlhsUWHkGDl3YQRkmHW2i-GMBma48RV9y4wucyZY8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});